import React, { useState, useRef } from 'react';
import { Camera, Wand2, ChevronLeft, Image as ImageIcon, Download, Share2, Loader2, X } from 'lucide-react';
import { generateRimDesign } from '../services/rimDesignService';

interface RimDesignFormProps {
  onBack: () => void;
}

export const RimDesignForm: React.FC<RimDesignFormProps> = ({ onBack }) => {
  const [originalPhoto, setOriginalPhoto] = useState<string | null>(null);
  const [generatedPhoto, setGeneratedPhoto] = useState<string | null>(null);
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const fileInputRef = useRef<HTMLInputElement>(null);

  const styles = [
    "Matte Black (啞黑)",
    "Chrome (電鍍銀)",
    "Gold (金色)",
    "Gunmetal (槍灰)",
    "Bronze (古銅)",
    "Red Sport (運動紅)",
    "Carbon Fiber (碳纖維)"
  ];

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setOriginalPhoto(reader.result as string);
        setGeneratedPhoto(null);
        setError(null);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleGenerate = async () => {
    if (!originalPhoto || !prompt) return;

    setIsGenerating(true);
    setError(null);

    try {
      const result = await generateRimDesign(originalPhoto, prompt);
      if (result) {
        setGeneratedPhoto(result);
      } else {
        setError("無法生成圖片，請重試。");
      }
    } catch (err) {
      setError("AI 服務暫時繁忙或發生錯誤。");
      console.error(err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleShare = async () => {
    if (generatedPhoto && navigator.share) {
      try {
        const blob = await (await fetch(generatedPhoto)).blob();
        const file = new File([blob], "new-rims.png", { type: "image/png" });
        await navigator.share({
          title: 'My New Rims',
          text: 'Check out this rim design generated by EB Tire AI!',
          files: [file],
        });
      } catch (err) {
        console.log("Share failed", err);
      }
    } else if (generatedPhoto) {
        // Fallback for desktop or non-share browsers
        const link = document.createElement('a');
        link.href = generatedPhoto;
        link.download = 'eb-tire-rim-design.png';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }
  };

  return (
    <div className="min-h-screen bg-brand-bg flex flex-col pb-20">
      {/* Header */}
      <div className="bg-brand-primary p-4 text-white flex items-center shadow-lg sticky top-0 z-40">
        <button onClick={onBack} className="mr-3 p-1 hover:bg-white/20 rounded-full transition-colors">
          <ChevronLeft className="w-6 h-6" />
        </button>
        <h2 className="text-lg font-bold flex items-center">
          <Wand2 className="w-5 h-5 mr-2" />
          AI 智能改鈴 (NanoBanana)
        </h2>
      </div>

      <div className="p-4 max-w-lg mx-auto w-full space-y-6">
        
        {/* Intro Text */}
        {!originalPhoto && (
            <div className="text-center p-4">
                <h3 className="text-2xl font-black text-brand-dark mb-2">預覽您的新輪圈</h3>
                <p className="text-gray-500 text-sm">
                    上傳您的愛車照片，讓 AI 為您更換輪圈顏色和風格。<br/>
                    (Take a photo of your car wheel to restyle it)
                </p>
            </div>
        )}

        {/* Image Display Area */}
        <div className="space-y-4">
            {!originalPhoto ? (
                <div 
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full aspect-[4/3] bg-white border-2 border-dashed border-brand-primary/30 rounded-3xl flex flex-col items-center justify-center cursor-pointer hover:bg-pink-50 transition-colors shadow-sm"
                >
                    <div className="bg-brand-light p-4 rounded-full mb-3">
                        <Camera className="w-8 h-8 text-brand-primary" />
                    </div>
                    <span className="font-bold text-brand-primary">拍攝/上傳照片</span>
                    <input 
                        type="file" 
                        accept="image/*" 
                        ref={fileInputRef} 
                        onChange={handleFileChange} 
                        className="hidden" 
                    />
                </div>
            ) : (
                <div className="relative w-full rounded-3xl overflow-hidden shadow-xl border-4 border-white">
                    <img 
                        src={generatedPhoto || originalPhoto} 
                        alt="Preview" 
                        className="w-full h-auto object-cover"
                    />
                    
                    {/* Reset Button */}
                    <button 
                        onClick={() => {
                            setOriginalPhoto(null);
                            setGeneratedPhoto(null);
                            setPrompt('');
                        }}
                        className="absolute top-3 right-3 bg-black/50 text-white p-2 rounded-full backdrop-blur-md hover:bg-red-500 transition-colors"
                    >
                        <X className="w-4 h-4" />
                    </button>

                    {/* Comparison Badge */}
                    <div className="absolute top-3 left-3 bg-white/80 text-brand-dark text-xs font-bold px-3 py-1 rounded-full backdrop-blur-md">
                        {generatedPhoto ? "AI Generated ✨" : "Original Photo"}
                    </div>

                    {isGenerating && (
                        <div className="absolute inset-0 bg-black/60 backdrop-blur-sm flex flex-col items-center justify-center text-white">
                            <Loader2 className="w-12 h-12 animate-spin mb-3 text-brand-primary" />
                            <p className="font-bold animate-pulse">AI 正在設計中...</p>
                            <p className="text-xs text-gray-300 mt-1">Generating new style</p>
                        </div>
                    )}
                </div>
            )}
        </div>

        {/* Controls */}
        {originalPhoto && !generatedPhoto && (
            <div className="bg-white p-5 rounded-3xl shadow-sm border border-brand-light animate-in fade-in slide-in-from-bottom-4">
                <label className="block text-sm font-bold text-gray-700 mb-3">
                    想要什麼風格? (Select Style)
                </label>
                
                {/* Style Chips */}
                <div className="flex flex-wrap gap-2 mb-4">
                    {styles.map(s => (
                        <button
                            key={s}
                            onClick={() => setPrompt(s)}
                            className={`px-3 py-2 rounded-xl text-xs font-bold transition-all ${
                                prompt === s 
                                ? 'bg-brand-primary text-white shadow-md scale-105' 
                                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                            }`}
                        >
                            {s}
                        </button>
                    ))}
                </div>

                {/* Custom Prompt Input */}
                <div className="relative">
                    <input
                        type="text"
                        value={prompt}
                        onChange={(e) => setPrompt(e.target.value)}
                        placeholder="或輸入自訂描述 (e.g., Neon Green)..."
                        className="w-full p-3 bg-gray-50 border border-gray-200 rounded-xl focus:ring-2 focus:ring-brand-primary outline-none text-sm"
                    />
                </div>

                <button
                    onClick={handleGenerate}
                    disabled={!prompt || isGenerating}
                    className={`w-full mt-4 py-3 rounded-2xl font-bold text-white shadow-lg flex items-center justify-center space-x-2 transition-all ${
                        !prompt 
                        ? 'bg-gray-300 cursor-not-allowed' 
                        : 'bg-gradient-to-r from-brand-primary to-brand-accent hover:shadow-brand-primary/50 active:scale-95'
                    }`}
                >
                    <Wand2 className="w-5 h-5" />
                    <span>立即生成 (Generate)</span>
                </button>
            </div>
        )}

        {/* Result Actions */}
        {generatedPhoto && (
            <div className="grid grid-cols-2 gap-3 animate-in fade-in slide-in-from-bottom-4">
                <button
                    onClick={() => setGeneratedPhoto(null)} // Revert to original to try again
                    className="py-3 bg-white border border-gray-200 text-gray-700 rounded-2xl font-bold shadow-sm flex items-center justify-center space-x-2 hover:bg-gray-50"
                >
                    <ImageIcon className="w-4 h-4" />
                    <span>再試一次</span>
                </button>
                <button
                    onClick={handleShare}
                    className="py-3 bg-brand-dark text-white rounded-2xl font-bold shadow-lg flex items-center justify-center space-x-2 hover:bg-brand-dark/90 active:scale-95"
                >
                    <Share2 className="w-4 h-4" />
                    <span>分享/儲存</span>
                </button>
            </div>
        )}

        {error && (
            <div className="p-4 bg-red-50 text-red-600 text-sm font-bold rounded-2xl text-center border border-red-100">
                {error}
            </div>
        )}
      </div>
    </div>
  );
};